// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Igual que Next.js: .env.local pisa a .env cuando existe (solo en la compu
// local — nunca se commitea, y en Railway no existe ese archivo). Así los
// comandos de Prisma CLI (db push, db seed, etc.) apuntan a la base local
// de Docker mientras se desarrolla, y no a producción por accidente.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
